#!/bin/sh

set -e

if [ "$1" != "configure" ]; then
    exit 0
fi

# Set permisions on default data and log directories on installation
if [ -z "$2" ]; then
    chown carbon:carbon /var/lib/graphite/whisper /var/log/go-carbon
fi

if invoke-rc.d go-carbon status >/dev/null; then
    echo "######################################"
    echo "# Please restart go-carbon manually. #"
    echo "######################################"
else
    invoke-rc.d go-carbon start || true
fi

#DEBHELPER#

exit 0
